# Generated by Django 5.2.6 on 2025-09-29 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atricle',
            new_name='Article',
        ),
    ]
